spring.application.name=EmployeeManagementSystem

# =========================================================
# SERVER CONFIGURATION
# =========================================================

# Port on which the Spring Boot application will run
server.port=8080


# =========================================================
# MYSQL DATABASE CONFIGURATION
# =========================================================

# MySQL database URL
# employee_management is the database/schema name
spring.datasource.url=jdbc:mysql://localhost:3306/employees_crud2

# MySQL username
spring.datasource.username=root

# MySQL password
spring.datasource.password=12589622

# MySQL JDBC driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE CONFIGURATION
# =========================================================

# Automatically update database tables based on entity changes
#
# update:
#   - Creates table if it doesn't exist
#   - Adds missing columns when required
#   - Does not normally delete existing data
#
# This is convenient for development.
# For production, we will discuss Flyway/Liquibase later.
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries generated by Hibernate in the console
spring.jpa.show-sql=true

# Format Hibernate SQL queries so they are easier to read
spring.jpa.properties.hibernate.format_sql=true

# Show SQL parameter values in Hibernate logs
# Useful during development/debugging
spring.jpa.properties.hibernate.highlight_sql=true

# Prevent Hibernate session from remaining open during the web response
spring.jpa.open-in-view=false


# =========================================================
# LOGGING CONFIGURATION
# =========================================================

# Root logging level
# INFO is recommended for normal development
logging.level.root=INFO

# Log Spring Web related information
logging.level.org.springframework.web=INFO

# Log Hibernate SQL statements
logging.level.org.hibernate.SQL=DEBUG

# Log Hibernate database binding information
# Useful when debugging SQL parameters
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# =========================================================
# LOG FILE CONFIGURATION
# =========================================================

# Write application logs to a file
logging.file.name=logs/employment-crud.log

# Maximum size of one log file
logging.logback.rollingpolicy.max-file-size=10MB

# Keep the previous log files
logging.logback.rollingpolicy.max-history=10


# =========================================================
# LOG MESSAGE FORMAT
# =========================================================

# Format of logs printed in the console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

# Format of logs written to the log file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

